---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: podinfo
  labels:
    app: podinfo
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~3.0
spec:
  releaseName: podinfo
  chart:
    git: git@github.com:johnlayton/monakplace
    ref: master
    path: cluster/charts/podinfo
  values:
    image:
      repository: stefanprodan/podinfo
      tag: 3.0.5
    service:
      enabled: true
      type: ClusterIP
    ingress:
      enabled: true
      path: /
      hosts:
      - podinfo.app.xip.io
