apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  labels:
    app: podinfo
  annotations:
    fluxcd.io/ignore: "false"
    fluxcd.io/automated: "true"
    fluxcd.io/tag.realtime: podinfo:~5.0
    fluxcd.io/locked: 'true'
spec:
  selector:
    matchLabels:
      app: podinfo
  replicas: 1
  template:
    metadata:
      labels:
        app: podinfo
    spec:
      containers:
        - name: podinfo
          image: stefanprodan/podinfo:5.0.1
          ports:
            - containerPort: 9898
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  labels:
    app: podinfo
spec:
  ports:
    - port: 80
      targetPort: 9898
  selector:
    app: podinfo
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: podinfo-ingress
spec:
  rules:
    - host: podinfo.app.xip.io
      http:
        paths:
          - path: /
            backend:
              serviceName: podinfo
              servicePort: 80